CREATE TABLE BRFSS_2011
(id serial,
_STATE integer,
IYEAR integer,
GENHLTH integer,
PHYSHLTH integer,
MENTHLTH integer,
POORHLTH integer,
HLTHPLN1 integer,
PERSDOC2 integer,
MEDCOST integer,
CHECKUP1 integer,
BPHIGH4 integer,
TOLDHI2 integer,
CVDINFR4 integer,
CVDCRHD4 integer,
CVDSTRK3 integer,
ASTHMA3 integer,
ASTHNOW integer,
CHCCOPD integer,
HAVARTH3 integer,
ADDEPEV2 integer,
CHCKIDNY integer,
DIABETE3 integer,
SMOKDAY2 integer,
USENOW3 integer,
MARITAL integer,
EDUCA integer,
EMPLOY integer,
INCOME2 integer,
RENTHOM1 integer,
SEX integer,
EXERANY2 integer,
ALCDAY5 integer,
BPHI2MR integer,
ADPLEASR integer,
ADDOWN integer,
ADSLEEP integer,
ADENERGY integer,
ADEAT1 integer,
ADFAIL integer,
ADTHINK integer,
ADMOVE integer,
MISTMNT integer,
ADANXEV integer,
SCNTMONY integer,
SCNTMEAL integer,
RACE2 integer,
_AGE_G integer,
HTM4 integer,
WTKG3 integer,
_BMI5 integer,
_FRUTSUM integer,
_VEGESUM integer,
PRIMARY KEY (_STATE,id)
);

CREATE TABLE STATES (
    _STATE INT   NOT NULL,
    STATE varchar   NOT NULL,
    PRIMARY KEY (_STATE),
    FOREIGN KEY (_STATE) REFERENCES BRFSS_2011 (_STATE)
);
